import time

print("============================================================\n")
print("             DETERMINISTIC LOGIC ENGINE\n")
print("============================================================\n")
print("Enter exit or bye to quit.\n")

responses = {
    "hello" : "Hello user! How can I help you today?",
    "hello bot" : "Hey! How can I help you?",
    "hi" : "Hi there! How is your day going?",
    "hi bot" : "Hey! How can I help you?",
    "good" : "Great to here, how can I assist you?",
    "fine" : "Nice! keep smiling.",
    "great" : "Awesome!",
    "bad" : "I hope things improve soon, I am here to help you.",
    "sad" : "Stay Strong!",
    "what are you" : "I am a deterministic White Box guardrail engine simulation.",
    "what can you do" : "I am a deterministic logic engine built to process user inputs, eliminate hallucination risks, and deliver completely safe, rule-based responses.",
    "help" : "Try asking me 'what are you' or 'what can you do' or 'what are basic AI concepts',type 'exit' to quit.",
    "what is hallucination" : "An AI hallucination is when an AI model confidently makes up false information that sounds completely real.",
    "what is rule based response" : "A rule-based response is an answer generated by a computer system using strict,pre-written if-then rules.",
    "understood" : "That's great to hear, is there anything I can help you with",
    "thank you" : "You're always welcome, I am here to help you anytime",
    "what are basic AI concepts" : "To understand AI, you should know about machine learning, deep learning, natural language processing, computer vision, and reinforcement learning. These concepts form the foundation of how AI systems learn and make decisions.",
    "what is ai" : "Artificial Intelligence is the simulation of human intelligence by machines.",
    "what is machine learning" : "Machine Learning is a branch of AI where systems learn from data instead of explicit programming.",
    "what is deep learning" : "Deep Learning uses neural networks with many layers to learn complex patterns.",
    "what is nlp" : "NLP stands for Natural Language Processing. It helps computers understand human language.",
    "what is chatbot" : "A chatbot is a software program designed to simulate human conversation.",
    "what is deterministic logic engine" : "A deterministic AI gives predefined outputs for predefined inputs using fixed logic.",
    "what is generative ai" : "Generative AI creates new content such as text, images, audio, or code.",
    "what is neural network" : "A neural network is a computing system inspired by the human brain.",
    "what is llm" : "LLM stands for Large Language Model. It is trained on massive text data to understand and generate language.",
    "what is computer vision" : "Computer Vision enables computers to understand and analyze images and videos."
}

while True:
    raw_input = input("\nYou:\n")
    clean_input = raw_input.lower().strip().rstrip("?")
    print("Bot:")
    if clean_input == "exit" or clean_input == "bye":
        print("It was nice talking to you, Bye.")
        break
    elif clean_input in responses:
        for char in responses[clean_input]:
            print(char, end="", flush = True)
            time.sleep(0.03)
    else :
        print("I do not understand.Type 'help' to see what I can do.")
